/* jshint esversion: 8 */

'use strict'

// parse_mud.js — one-off generator: reads the C64 client's master
// muddle file (new.mud in the MADE repo) and emits lib/classes.js, the
// class-to-resource table. Run whenever the port needs re-syncing:
//
//   node lib/tools/parse_mud.js [path-to-new.mud] > lib/classes.js
//
// Only the action (behavior) slots become live dispatch data; sound and
// image resource names are carried through as strings to reserve the
// shape for a future renderer client.

const fs = require('fs')
const path = require('path')

const DEFAULT_MUD = path.join(
  process.env.HOME || '', 'habitat-orig/sources/c64/Behaviors/new.mud')

// new.mud class name → server mod type name. Default derivation is
// strip `class_` and capitalize the first letter (class_magic_lamp →
// Magic_lamp), which matches the Java mod class names for all but:
const TYPE_NAME_EXCEPTIONS = {
  class_teleport_booth: 'Teleport',
  class_wind_up_toy: 'Windup_toy',
}

function typeNameFor(mudName) {
  if (TYPE_NAME_EXCEPTIONS[mudName]) return TYPE_NAME_EXCEPTIONS[mudName]
  const stripped = mudName.replace(/^class_/, '')
  return stripped.charAt(0).toUpperCase() + stripped.slice(1)
}

function parse(text) {
  // Strip /* */ comments but keep their text per-line for slot
  // annotations in the generated output.
  const classes = []
  let current = null

  for (const rawLine of text.split('\n')) {
    const comment = (rawLine.match(/\/\*\s*(.*?)\s*\*\//) || [])[1] || ''
    const line = rawLine.replace(/\/\*.*?\*\//g, '').trim()

    const classMatch = line.match(/^class\s+([A-Za-z_][A-Za-z0-9_]*)\s+(\d+)\s*\{/)
    if (classMatch) {
      current = {
        mudName: classMatch[1],
        number: parseInt(classMatch[2], 10),
        actions: [],
        actionComments: [],
        sounds: [],
      }
      classes.push(current)
      continue
    }
    if (!current) continue

    if (line === '}') { current = null; continue }

    const m = line.match(/^(action|sound)\s+([A-Za-z_][A-Za-z0-9_]*)\s*$/)
    if (!m) {
      if (/^action|^sound/.test(line)) {
        throw new Error(`parse_mud: unparseable ${current.mudName} line: ${JSON.stringify(rawLine)}`)
      }
      continue // image/head/byte lines — not carried yet
    }
    if (m[1] === 'action') {
      current.actions.push(m[2])
      current.actionComments.push(comment)
    } else {
      current.sounds.push(m[2])
    }
  }
  return classes
}

function generate(classes) {
  const out = []
  out.push('/* jshint esversion: 8 */')
  out.push("'use strict'")
  out.push('')
  out.push('// GENERATED by lib/tools/parse_mud.js from the C64 client master')
  out.push('// muddle file (MADE repo, sources/c64/Behaviors/new.mud) — do not')
  out.push('// hand-edit; re-run the generator instead.')
  out.push('//')
  out.push('// Action slot semantics: 0-7 are the user verbs (DO, reverseDO, GO,')
  out.push('// STOP, GET, PUT, TALK, DESTROY — ACTION_* in lib/constants.js);')
  out.push('// slots 8+ are host-message handlers (avatar/region: slot number ==')
  out.push('// host message number) or class-internal chain targets. Entries are')
  out.push('// behavior names resolved against lib/behaviors at dispatch time so')
  out.push('// unported behaviors fail loudly rather than break the table load.')
  out.push('// Sound slots are carried as names only, for a future renderer.')
  out.push('')
  out.push('const classes = {')
  for (const c of classes) {
    out.push(`  ${c.number}: {`)
    out.push(`    name: '${c.mudName}',`)
    out.push(`    typeName: '${typeNameFor(c.mudName)}',`)
    out.push('    actions: [')
    c.actions.forEach((a, i) => {
      const note = c.actionComments[i] ? ` // ${i}: ${c.actionComments[i]}` : ` // ${i}`
      out.push(`      '${a}',${note}`)
    })
    out.push('    ],')
    if (c.sounds.length) {
      out.push(`    sounds: [${c.sounds.map((s) => `'${s}'`).join(', ')}],`)
    } else {
      out.push('    sounds: [],')
    }
    out.push('  },')
  }
  out.push('}')
  out.push('')
  out.push('const byTypeName = {}')
  out.push('for (const [num, entry] of Object.entries(classes)) {')
  out.push('  byTypeName[entry.typeName] = parseInt(num, 10)')
  out.push('}')
  out.push('')
  out.push('module.exports = { classes, byTypeName }')
  out.push('')
  return out.join('\n')
}

const mudPath = process.argv[2] || DEFAULT_MUD
const classes = parse(fs.readFileSync(mudPath, 'utf8'))
process.stderr.write(`parse_mud: ${classes.length} classes, ` +
  `${classes.reduce((n, c) => n + c.actions.length, 0)} action slots\n`)
process.stdout.write(generate(classes))
