/* jshint esversion: 8 */

'use strict'

// parse_mud.js — one-off generator: reads the C64 client's master
// muddle file and emits lib/classes.js, the class-to-resource table.
//
//   node lib/tools/parse_mud.js [path-to.mud] > lib/classes.js
//
// Only the action (behavior) slots become live dispatch data; sound and
// image resource names are carried through as strings to reserve the
// shape for a future renderer client.
//
// ── CANONICAL SOURCE ────────────────────────────────────────────────
// The real client database is built from ONE muddle file, and that file
// is:
//
//     ~/habitat-orig/habitat/Beta/Bak/beta.mud
//
// Evidence (2026-06):
//   * Best match to the server's authoritative class numbers in
//     src/main/java/.../Constants.java — 98/104 (the misses are just
//     name spellings, e.g. escape_device/escape_dev, teleport_booth/
//     teleport). Every other .mud scores lower.
//   * Contains the NeoHabitat classes the running server uses that the
//     older files lack: Elevator(28), Die(21), Plaque(55),
//     Magic_immobile(97), Pawn_machine(96), Game_piece(5), ...
//   * Its behaviors agree with the Java mods where the older
//     sources/c64/Behaviors/new.mud does NOT:
//       - Flag extends Massive → GET is mass-gated: beta uses
//         generic_getMass (correct); new.mud uses generic_goToAndGet.
//       - Mailbox.java is inert (no verb handlers; mail moved to
//         Paper/Avatar/Dropbox): beta's Mailbox is noEffect/noEffect
//         (correct); new.mud still has the obsolete mailbox_get /
//         generic_sendMail / mailbox_MAILARRIVED — a sure sign it is
//         a much older version.
//
// DEFAULT_MUD below still points at the older new.mud because the
// committed lib/classes.js was generated from it; regenerating from
// beta.mud is the planned migration (it introduces ~21 not-yet-ported
// behaviors — elevator_talk, generic_rdoMagic, trap_put, ... — that
// must be ported or left as loud `unported` stubs).

const fs = require('fs')
const path = require('path')

// The canonical client muddle file (see the CANONICAL SOURCE note above).
// The committed classes.js predates this finding and came from new.mud;
// regenerate with `node parse_mud.js "$CANONICAL_MUD" > lib/classes.js`
// once the ~21 beta-only behaviors are ported.
const CANONICAL_MUD = path.join(
  process.env.HOME || '', 'habitat-orig/habitat/Beta/Bak/beta.mud')

// What the current committed lib/classes.js was actually generated from
// (older; wrong for Flag/Mailbox/etc.). Kept as the default only to match
// the committed output until the migration to CANONICAL_MUD happens.
const DEFAULT_MUD = path.join(
  process.env.HOME || '', 'habitat-orig/sources/c64/Behaviors/new.mud')

// new.mud class name → server mod type name. Default derivation is
// strip `class_` and capitalize the first letter (class_magic_lamp →
// Magic_lamp), which matches the Java mod class names for all but:
const TYPE_NAME_EXCEPTIONS = {
  class_teleport_booth: 'Teleport',
  class_wind_up_toy: 'Windup_toy',
}

function typeNameFor(mudName) {
  if (TYPE_NAME_EXCEPTIONS[mudName]) return TYPE_NAME_EXCEPTIONS[mudName]
  const stripped = mudName.replace(/^class_/, '')
  return stripped.charAt(0).toUpperCase() + stripped.slice(1)
}

function parse(text) {
  // Strip /* */ comments but keep their text per-line for slot
  // annotations in the generated output.
  const classes = []
  let current = null

  for (const rawLine of text.split('\n')) {
    const comment = (rawLine.match(/\/\*\s*(.*?)\s*\*\//) || [])[1] || ''
    const line = rawLine.replace(/\/\*.*?\*\//g, '').trim()

    const classMatch = line.match(/^class\s+([A-Za-z_][A-Za-z0-9_]*)\s+(\d+)\s*\{/)
    if (classMatch) {
      current = {
        mudName: classMatch[1],
        number: parseInt(classMatch[2], 10),
        actions: [],
        actionComments: [],
        sounds: [],
      }
      classes.push(current)
      continue
    }
    if (!current) continue

    if (line === '}') { current = null; continue }

    const m = line.match(/^(action|sound)\s+([A-Za-z_][A-Za-z0-9_]*)\s*$/)
    if (!m) {
      if (/^action|^sound/.test(line)) {
        throw new Error(`parse_mud: unparseable ${current.mudName} line: ${JSON.stringify(rawLine)}`)
      }
      continue // image/head/byte lines — not carried yet
    }
    if (m[1] === 'action') {
      current.actions.push(m[2])
      current.actionComments.push(comment)
    } else {
      current.sounds.push(m[2])
    }
  }
  return classes
}

function generate(classes, sourceLabel) {
  const out = []
  out.push('/* jshint esversion: 8 */')
  out.push("'use strict'")
  out.push('')
  out.push('// GENERATED by lib/tools/parse_mud.js from the canonical C64 client')
  out.push(`// muddle file (${sourceLabel}) — do not`)
  out.push('// hand-edit; re-run the generator instead.')
  out.push('//')
  out.push('// Action slot semantics: 0-7 are the user verbs (DO, reverseDO, GO,')
  out.push('// STOP, GET, PUT, TALK, DESTROY — ACTION_* in lib/constants.js);')
  out.push('// slots 8+ are host-message handlers (avatar/region: slot number ==')
  out.push('// host message number) or class-internal chain targets. Entries are')
  out.push('// behavior names resolved against lib/behaviors at dispatch time so')
  out.push('// unported behaviors fail loudly rather than break the table load.')
  out.push('// Sound slots are carried as names only, for a future renderer.')
  out.push('')
  out.push('const classes = {')
  for (const c of classes) {
    out.push(`  ${c.number}: {`)
    out.push(`    name: '${c.mudName}',`)
    out.push(`    typeName: '${typeNameFor(c.mudName)}',`)
    out.push('    actions: [')
    c.actions.forEach((a, i) => {
      const note = c.actionComments[i] ? ` // ${i}: ${c.actionComments[i]}` : ` // ${i}`
      out.push(`      '${a}',${note}`)
    })
    out.push('    ],')
    if (c.sounds.length) {
      out.push(`    sounds: [${c.sounds.map((s) => `'${s}'`).join(', ')}],`)
    } else {
      out.push('    sounds: [],')
    }
    out.push('  },')
  }
  out.push('}')
  out.push('')
  out.push('const byTypeName = {}')
  out.push('for (const [num, entry] of Object.entries(classes)) {')
  out.push('  byTypeName[entry.typeName] = parseInt(num, 10)')
  out.push('}')
  out.push('')
  out.push('module.exports = { classes, byTypeName }')
  out.push('')
  return out.join('\n')
}

// Default to the CANONICAL source now that the migration is happening.
// (DEFAULT_MUD is retained above only as a documented reference to the old
// file the prior classes.js came from.)
const mudPath = process.argv[2] || CANONICAL_MUD
const classes = parse(fs.readFileSync(mudPath, 'utf8'))
const sourceLabel = mudPath.replace(process.env.HOME || '', '~')
process.stderr.write(`parse_mud: ${classes.length} classes, ` +
  `${classes.reduce((n, c) => n + c.actions.length, 0)} action slots from ${sourceLabel}\n`)
process.stdout.write(generate(classes, sourceLabel))
