version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/pushserver"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/habibots"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/db"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/tools/vice_login_driver"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/tools/log-parser"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/bridge_v2"
    schedule:
      interval: "weekly"
