#!/bin/bash
# Builds the Neoclassical Habitat Elko server.

set -eo pipefail

ELKO_VERSION="2.0.4-SNAPSHOT"

# Downloads the latest version of Elkoserver if we have not yet done so.
if [ ! -e ./lib/elkoserver-${ELKO_VERSION}.jar ]; then
  mkdir -p lib
  wget -O ./lib/elkoserver-${ELKO_VERSION}.jar \
    https://s3.amazonaws.com/ssalevan/Elko/elkoserver-${ELKO_VERSION}.jar
  wget -O ./lib/elkoserver-${ELKO_VERSION}-sources.jar \
    https://s3.amazonaws.com/ssalevan/Elko/elkoserver-${ELKO_VERSION}-sources.jar
fi

# Installs the Elkoserver JAR into the local Maven repository.
mvn install:install-file \
  -Dfile=./lib/elkoserver-${ELKO_VERSION}.jar \
  -Dsources=./lib/elkoserver-${ELKO_VERSION}-sources.jar \
  -DgroupId=org.elko \
  -DartifactId=elkoserver \
  -Dversion="${ELKO_VERSION}" \
  -Dpackaging=jar \
  -DgeneratePom=true

mvn package
