make Hatchery/hatchery.o
make Popustop/Popustop.100.o
make Popustop/Popustop.106.o
make Popustop/Popustop.108.o
make Popustop/Popustop.109.o
make Popustop/Popustop.110.o
make Popustop/Popustop.112.o
make Popustop/Popustop.120.o
make Popustop/Popustop.121.o
make Popustop/Popustop.125.o
make Popustop/Popustop.129.o
make Popustop/Popustop.131.o
make Popustop/Popustop.134.o
make Popustop/Popustop.141.o
make Popustop/Popustop.144.o
make Popustop/Popustop.147.o
make Popustop/Popustop.152.o
make Popustop/Popustop.158.o
make Popustop/Popustop.167.o
make Popustop/Popustop.170.o
make Popustop/Popustop.elevator1.line1055.o
make Popustop/Popustop.elevator1.line155.o
make Popustop/Popustop.elevator1.line255.o
make Popustop/Popustop.elevator1.line355.o
make Popustop/Popustop.elevator1.line455.o
make Popustop/Popustop.elevator1.line55.o
make Popustop/Popustop.elevator1.line555.o
make Popustop/Popustop.elevator1.line655.o
make Popustop/Popustop.elevator1.line755.o
make Popustop/Popustop.elevator1.line855.o
make Popustop/Popustop.elevator1.line955.o
make Popustop/Popustop.stairs.line1021.o
make Popustop/Popustop.stairs.line121.o
make Popustop/Popustop.stairs.line21.o
make Popustop/Popustop.stairs.line221.o
make Popustop/Popustop.stairs.line321.o
make Popustop/Popustop.stairs.line421.o
make Popustop/Popustop.stairs.line521.o
make Popustop/Popustop.stairs.line621.o
make Popustop/Popustop.stairs.line721.o
make Popustop/Popustop.stairs.line821.o
make Popustop/Popustop.stairs.line921.o
make Streets/OutamyWy_529_interior.o
make new_Downtown/Downtown_1972.o
make new_Downtown/Downtown_1976.o
make new_Downtown/Downtown_1979.o
make new_Downtown/Downtown_1980.o
make new_Downtown/Downtown_3d.o
make new_Downtown/Downtown_3g.o
make new_Downtown/Downtown_3h.o
make new_Downtown/Downtown_3i.o
make new_Downtown/Downtown_4b.o
make new_Downtown/Downtown_4d.o
make new_Downtown/Downtown_4j.o
make new_Downtown/Downtown_5b.o
make new_Downtown/Downtown_5d.o
make new_Downtown/Downtown_5h.o
make new_Downtown/Downtown_5j.o
make new_Downtown/Downtown_6b.o
make new_Downtown/Downtown_6d.o
make new_Downtown/Downtown_7b.o
make new_Downtown/Downtown_7c.o
make new_Downtown/Downtown_7d.o
make new_Downtown/Downtown_7e.o
make new_Downtown/Downtown_7g.o
make new_Downtown/Downtown_7i.o
make new_Downtown/Downtown_8g.o
make new_Downtown/Downtown_9108.o
make new_Downtown/Downtown_9174.o
make new_Downtown/Downtown_9175.o
make new_Downtown/Downtown_9176.o
make new_Downtown/Downtown_9177.o
make new_Downtown/Downtown_9178.o
make new_Downtown/Downtown_9179.o
make new_Downtown/Downtown_9191.o
make new_Downtown/Downtown_9192.o
make new_Downtown/Downtown_9193.o
make new_Downtown/Downtown_9208.o
make new_Downtown/Downtown_9209.o
make new_Downtown/Downtown_9215.o
make new_Downtown/Downtown_9216.o
make new_Downtown/Downtown_9229.o
make new_Downtown/Downtown_9230.o
make new_Downtown/Downtown_9231.o
make new_Downtown/Downtown_9232.o
make new_Downtown/Downtown_9233.o 
make new_Downtown/Downtown_9174.o
make new_Downtown/Downtown_9175.o
make new_Downtown/Downtown_9176.o
make new_Downtown/Downtown_9177.o
make new_Downtown/Downtown_9178.o
make new_Downtown/Downtown_9179.o
make new_Downtown/Downtown_9191.o
make new_Downtown/Downtown_9192.o
make new_Downtown/Downtown_9193.o
make new_Downtown/Downtown_9208.o
make new_Downtown/Downtown_9209.o
make new_Downtown/Downtown_9215.o
make new_Downtown/Downtown_9216.o
make new_Downtown/Downtown_9229.o
make new_Downtown/Downtown_9230.o
make new_Downtown/Downtown_9231.o
make new_Downtown/Downtown_9232.o
make new_Downtown/Downtown_9233.o
make Capture_flag/CTF_6405.o
make Capture_flag/CTF_7000.o
make Capture_flag/CTF_7001.o
make Capture_flag/CTF_7002.o
make Capture_flag/CTF_7003.o
make Capture_flag/CTF_7004.o
make Capture_flag/CTF_7010.o
make Capture_flag/CTF_7011.o
make Capture_flag/CTF_7012.o
make Capture_flag/CTF_7013.o
make Capture_flag/CTF_7014.o
make Capture_flag/CTF_7015.o
make Capture_flag/CTF_7016.o
make Capture_flag/CTF_7017.o
make Capture_flag/CTF_7018.o
make Capture_flag/CTF_7019.o
make Capture_flag/CTF_7020.o
make I5/I5_1310.o
make I5/I5_7209.o
make I5/I5_7210.o
make Text/text-captureflag.o
make Text/text-captureflagunused.o
make Woods/Woods_gr.o
make Woods/Woods_gs.o
