make Streets/Bleem_St_108_front.o
make Streets/Bleem_St_108_interior.o
make Streets/Bleem_St_18_front.o
make Streets/Bleem_St_18_interior.o
make Streets/Bleem_St_28_front.o
make Streets/Bleem_St_28_interior.o
make Streets/Bleem_St_38_front.o
make Streets/Bleem_St_38_interior.o
make Streets/Bleem_St_48_front.o
make Streets/Bleem_St_48_interior.o
make Streets/Bleem_St_58_front.o
make Streets/Bleem_St_58_interior.o
make Streets/Bleem_St_68_front.o
make Streets/Bleem_St_68_interior.o
make Streets/Bleem_St_78_front.o
make Streets/Bleem_St_78_interior.o
make Streets/Bleem_St_88_front.o
make Streets/Bleem_St_88_interior.o
make Streets/Bleem_St_98_front.o
make Streets/Bleem_St_98_interior.o
make Streets/Bleem_St_cross.o
make Streets/Bleem_St_n_end.o
make Streets/Bleem_St_s_end.o
make Streets/Cross_Rd_cross.o
make Streets/Fast_Ln_1024_front.o
make Streets/Fast_Ln_1024_interior.o
make Streets/Fast_Ln_124_front.o
make Streets/Fast_Ln_124_interior.o
make Streets/Fast_Ln_224_front.o
make Streets/Fast_Ln_224_interior.o
make Streets/Fast_Ln_324_front.o
make Streets/Fast_Ln_324_interior.o
make Streets/Fast_Ln_424_front.o
make Streets/Fast_Ln_424_interior.o
make Streets/Fast_Ln_524_front.o
make Streets/Fast_Ln_524_interior.o
make Streets/Fast_Ln_624_front.o
make Streets/Fast_Ln_624_interior.o
make Streets/Fast_Ln_724_front.o
make Streets/Fast_Ln_724_interior.o
make Streets/Fast_Ln_824_front.o
make Streets/Fast_Ln_824_interior.o
make Streets/Fast_Ln_924_front.o
make Streets/Fast_Ln_924_interior.o
make Streets/Fast_Ln_cross.o
make Streets/Fast_Ln_n_end.o
make Streets/Fast_Ln_s_end.o
make Streets/Foon_Ave_107_front.o
make Streets/Foon_Ave_107_interior.o
make Streets/Foon_Ave_17_front.o
make Streets/Foon_Ave_17_interior.o
make Streets/Foon_Ave_27_front.o
make Streets/Foon_Ave_27_interior.o
make Streets/Foon_Ave_37_front.o
make Streets/Foon_Ave_37_interior.o
make Streets/Foon_Ave_47_front.o
make Streets/Foon_Ave_47_interior.o
make Streets/Foon_Ave_57_front.o
make Streets/Foon_Ave_57_interior.o
make Streets/Foon_Ave_67_front.o
make Streets/Foon_Ave_67_interior.o
make Streets/Foon_Ave_77_front.o
make Streets/Foon_Ave_77_interior.o
make Streets/Foon_Ave_87_front.o
make Streets/Foon_Ave_87_interior.o
make Streets/Foon_Ave_97_front.o
make Streets/Foon_Ave_97_interior.o
make Streets/Foon_Ave_cross.o
make Streets/Foon_Ave_n_end.o
make Streets/Foon_Ave_s_end.o
make Streets/Janice_Ln_1025_front.o
make Streets/Janice_Ln_1025_interior.o
make Streets/Janice_Ln_125_front.o
make Streets/Janice_Ln_125_interior.o
make Streets/Janice_Ln_225_front.o
make Streets/Janice_Ln_225_interior.o
make Streets/Janice_Ln_325_front.o
make Streets/Janice_Ln_325_interior.o
make Streets/Janice_Ln_425_front.o
make Streets/Janice_Ln_425_interior.o
make Streets/Janice_Ln_525_front.o
make Streets/Janice_Ln_525_interior.o
make Streets/Janice_Ln_625_front.o
make Streets/Janice_Ln_625_interior.o
make Streets/Janice_Ln_725_front.o
make Streets/Janice_Ln_725_interior.o
make Streets/Janice_Ln_825_front.o
make Streets/Janice_Ln_825_interior.o
make Streets/Janice_Ln_925_front.o
make Streets/Janice_Ln_925_interior.o
make Streets/Janice_Ln_cross.o
make Streets/Janice_Ln_n_end.o
make Streets/Janice_Ln_s_end.o
make Streets/Kerner_1016_front.o
make Streets/Kerner_1016_interior.o
make Streets/Kerner_116_front.o
make Streets/Kerner_116_interior.o
make Streets/Kerner_216_front.o
make Streets/Kerner_216_interior.o
make Streets/Kerner_316_front.o
make Streets/Kerner_316_interior.o
make Streets/Kerner_416_front.o
make Streets/Kerner_416_interior.o
make Streets/Kerner_516_front.o
make Streets/Kerner_516_interior.o
make Streets/Kerner_616_front.o
make Streets/Kerner_616_interior.o
make Streets/Kerner_716_front.o
make Streets/Kerner_716_interior.o
make Streets/Kerner_816_front.o
make Streets/Kerner_816_interior.o
make Streets/Kerner_916_front.o
make Streets/Kerner_916_interior.o
make Streets/Kerner_cross.o
make Streets/Kerner_n_end.o
make Streets/Kerner_s_end.o
make Streets/Kings_Rd_1010_front.o
make Streets/Kings_Rd_1010_interior.o
make Streets/Kings_Rd_110_front.o
make Streets/Kings_Rd_110_interior.o
make Streets/Kings_Rd_210_front.o
make Streets/Kings_Rd_210_interior.o
make Streets/Kings_Rd_310_front.o
make Streets/Kings_Rd_310_interior.o
make Streets/Kings_Rd_410_front.o
make Streets/Kings_Rd_410_interior.o
make Streets/Kings_Rd_510_front.o
make Streets/Kings_Rd_510_interior.o
make Streets/Kings_Rd_610_front.o
make Streets/Kings_Rd_610_interior.o
make Streets/Kings_Rd_710_front.o
make Streets/Kings_Rd_710_interior.o
make Streets/Kings_Rd_810_front.o
make Streets/Kings_Rd_810_interior.o
make Streets/Kings_Rd_910_front.o
make Streets/Kings_Rd_910_interior.o
make Streets/Kings_Rd_cross.o
make Streets/Kings_Rd_e_end.o
make Streets/Kings_Rd_w_end.o
make Streets/Kludge_Ct_1018_front.o
make Streets/Kludge_Ct_1018_interior.o
make Streets/Kludge_Ct_118_front.o
make Streets/Kludge_Ct_118_interior.o
make Streets/Kludge_Ct_218_front.o
make Streets/Kludge_Ct_218_interior.o
make Streets/Kludge_Ct_318_front.o
make Streets/Kludge_Ct_318_interior.o
make Streets/Kludge_Ct_418_front.o
make Streets/Kludge_Ct_418_interior.o
make Streets/Kludge_Ct_518_front.o
make Streets/Kludge_Ct_518_interior.o
make Streets/Kludge_Ct_618_front.o
make Streets/Kludge_Ct_618_interior.o
make Streets/Kludge_Ct_718_front.o
make Streets/Kludge_Ct_718_interior.o
make Streets/Kludge_Ct_818_front.o
make Streets/Kludge_Ct_818_interior.o
make Streets/Kludge_Ct_918_front.o
make Streets/Kludge_Ct_918_interior.o
make Streets/Kludge_Ct_cross.o
make Streets/Kludge_Ct_n_end.o
make Streets/Kludge_Ct_s_end.o
make Streets/Milky_Wy_1028_front.o
make Streets/Milky_Wy_1028_interior.o
make Streets/Milky_Wy_128_front.o
make Streets/Milky_Wy_128_interior.o
make Streets/Milky_Wy_228_front.o
make Streets/Milky_Wy_228_interior.o
make Streets/Milky_Wy_328_front.o
make Streets/Milky_Wy_328_interior.o
make Streets/Milky_Wy_428_front.o
make Streets/Milky_Wy_428_interior.o
make Streets/Milky_Wy_528_front.o
make Streets/Milky_Wy_528_interior.o
make Streets/Milky_Wy_628_front.o
make Streets/Milky_Wy_628_interior.o
make Streets/Milky_Wy_728_front.o
make Streets/Milky_Wy_728_interior.o
make Streets/Milky_Wy_828_front.o
make Streets/Milky_Wy_828_interior.o
make Streets/Milky_Wy_928_front.o
make Streets/Milky_Wy_928_interior.o
make Streets/Milky_Wy_cross.o
make Streets/Milky_Wy_n_end.o
make Streets/Milky_Wy_s_end.o
make Streets/OutamyWy_cross.o
make Streets/Pam_Pl_1014_front.o
make Streets/Pam_Pl_1014_interior.o
make Streets/Pam_Pl_114_front.o
make Streets/Pam_Pl_114_interior.o
make Streets/Pam_Pl_214_front.o
make Streets/Pam_Pl_214_interior.o
make Streets/Pam_Pl_314_front.o
make Streets/Pam_Pl_314_interior.o
make Streets/Pam_Pl_414_front.o
make Streets/Pam_Pl_414_interior.o
make Streets/Pam_Pl_514_front.o
make Streets/Pam_Pl_514_interior.o
make Streets/Pam_Pl_614_front.o
make Streets/Pam_Pl_614_interior.o
make Streets/Pam_Pl_714_front.o
make Streets/Pam_Pl_714_interior.o
make Streets/Pam_Pl_814_front.o
make Streets/Pam_Pl_814_interior.o
make Streets/Pam_Pl_914_front.o
make Streets/Pam_Pl_914_interior.o
make Streets/Pam_Pl_cross.o
make Streets/Pam_Pl_e_end.o
make Streets/Pam_Pl_w_end.o
make Streets/Pokey_Pl_1022_front.o
make Streets/Pokey_Pl_1022_interior.o
make Streets/Pokey_Pl_122_front.o
make Streets/Pokey_Pl_122_interior.o
make Streets/Pokey_Pl_222_front.o
make Streets/Pokey_Pl_222_interior.o
make Streets/Pokey_Pl_322_front.o
make Streets/Pokey_Pl_322_interior.o
make Streets/Pokey_Pl_422_front.o
make Streets/Pokey_Pl_422_interior.o
make Streets/Pokey_Pl_522_front.o
make Streets/Pokey_Pl_522_interior.o
make Streets/Pokey_Pl_622_front.o
make Streets/Pokey_Pl_622_interior.o
make Streets/Pokey_Pl_722_front.o
make Streets/Pokey_Pl_722_interior.o
make Streets/Pokey_Pl_822_front.o
make Streets/Pokey_Pl_822_interior.o
make Streets/Pokey_Pl_922_front.o
make Streets/Pokey_Pl_922_interior.o
make Streets/Pokey_Pl_cross.o
make Streets/Pokey_Pl_e_end.o
make Streets/Pokey_Pl_w_end.o
make Streets/Rocky_Rd_1015_front.o
make Streets/Rocky_Rd_1015_interior.o
make Streets/Rocky_Rd_115_front.o
make Streets/Rocky_Rd_115_interior.o
make Streets/Rocky_Rd_215_front.o
make Streets/Rocky_Rd_215_interior.o
make Streets/Rocky_Rd_315_front.o
make Streets/Rocky_Rd_315_interior.o
make Streets/Rocky_Rd_415_front.o
make Streets/Rocky_Rd_415_interior.o
make Streets/Rocky_Rd_515_front.o
make Streets/Rocky_Rd_515_interior.o
make Streets/Rocky_Rd_615_front.o
make Streets/Rocky_Rd_615_interior.o
make Streets/Rocky_Rd_715_front.o
make Streets/Rocky_Rd_715_interior.o
make Streets/Rocky_Rd_815_front.o
make Streets/Rocky_Rd_815_interior.o
make Streets/Rocky_Rd_915_front.o
make Streets/Rocky_Rd_915_interior.o
make Streets/Rocky_Rd_cross.o
make Streets/Rocky_Rd_e_end.o
make Streets/Rocky_Rd_w_end.o
make Streets/Saint_St_1019_front.o
make Streets/Saint_St_1019_interior.o
make Streets/Saint_St_119_front.o
make Streets/Saint_St_119_interior.o
make Streets/Saint_St_219_front.o
make Streets/Saint_St_219_interior.o
make Streets/Saint_St_319_front.o
make Streets/Saint_St_319_interior.o
make Streets/Saint_St_419_front.o
make Streets/Saint_St_419_interior.o
make Streets/Saint_St_519_front.o
make Streets/Saint_St_519_interior.o
make Streets/Saint_St_619_front.o
make Streets/Saint_St_619_interior.o
make Streets/Saint_St_719_front.o
make Streets/Saint_St_719_interior.o
make Streets/Saint_St_819_front.o
make Streets/Saint_St_819_interior.o
make Streets/Saint_St_919_front.o
make Streets/Saint_St_919_interior.o
make Streets/Saint_St_cross.o
make Streets/Saint_St_e_end.o
make Streets/Saint_St_w_end.o
make Streets/Spiff_Ln_1011_front.o
make Streets/Spiff_Ln_1011_interior.o
make Streets/Spiff_Ln_111_front.o
make Streets/Spiff_Ln_111_interior.o
make Streets/Spiff_Ln_211_front.o
make Streets/Spiff_Ln_211_interior.o
make Streets/Spiff_Ln_311_front.o
make Streets/Spiff_Ln_311_interior.o
make Streets/Spiff_Ln_411_front.o
make Streets/Spiff_Ln_411_interior.o
make Streets/Spiff_Ln_511_front.o
make Streets/Spiff_Ln_511_interior.o
make Streets/Spiff_Ln_611_front.o
make Streets/Spiff_Ln_611_interior.o
make Streets/Spiff_Ln_711_front.o
make Streets/Spiff_Ln_711_interior.o
make Streets/Spiff_Ln_811_front.o
make Streets/Spiff_Ln_811_interior.o
make Streets/Spiff_Ln_911_front.o
make Streets/Spiff_Ln_911_interior.o
make Streets/Spiff_Ln_cross.o
make Streets/Spiff_Ln_e_end.o
make Streets/Spiff_Ln_w_end.o
make Streets/Wacka_Rd_109_front.o
make Streets/Wacka_Rd_109_interior.o
make Streets/Wacka_Rd_19_front.o
make Streets/Wacka_Rd_19_interior.o
make Streets/Wacka_Rd_29_front.o
make Streets/Wacka_Rd_29_interior.o
make Streets/Wacka_Rd_39_front.o
make Streets/Wacka_Rd_39_interior.o
make Streets/Wacka_Rd_49_front.o
make Streets/Wacka_Rd_49_interior.o
make Streets/Wacka_Rd_59_front.o
make Streets/Wacka_Rd_59_interior.o
make Streets/Wacka_Rd_69_front.o
make Streets/Wacka_Rd_69_interior.o
make Streets/Wacka_Rd_79_front.o
make Streets/Wacka_Rd_79_interior.o
make Streets/Wacka_Rd_89_front.o
make Streets/Wacka_Rd_89_interior.o
make Streets/Wacka_Rd_99_front.o
make Streets/Wacka_Rd_99_interior.o
make Streets/Wacka_Rd_cross.o
make Streets/Wacka_Rd_e_end.o
make Streets/Wacka_Rd_w_end.o
make Streets/Warp_Dr_1023_front.o
make Streets/Warp_Dr_1023_interior.o
make Streets/Warp_Dr_123_front.o
make Streets/Warp_Dr_123_interior.o
make Streets/Warp_Dr_223_front.o
make Streets/Warp_Dr_223_interior.o
make Streets/Warp_Dr_323_front.o
make Streets/Warp_Dr_323_interior.o
make Streets/Warp_Dr_423_front.o
make Streets/Warp_Dr_423_interior.o
make Streets/Warp_Dr_523_front.o
make Streets/Warp_Dr_523_interior.o
make Streets/Warp_Dr_623_front.o
make Streets/Warp_Dr_623_interior.o
make Streets/Warp_Dr_723_front.o
make Streets/Warp_Dr_723_interior.o
make Streets/Warp_Dr_823_front.o
make Streets/Warp_Dr_823_interior.o
make Streets/Warp_Dr_923_front.o
make Streets/Warp_Dr_923_interior.o
make Streets/Warp_Dr_cross.o
make Streets/Warp_Dr_n_end.o
make Streets/Warp_Dr_s_end.o
make Streets/Wazoo_St_1012_front.o
make Streets/Wazoo_St_1012_interior.o
make Streets/Wazoo_St_112_front.o
make Streets/Wazoo_St_112_interior.o
make Streets/Wazoo_St_212_front.o
make Streets/Wazoo_St_212_interior.o
make Streets/Wazoo_St_312_front.o
make Streets/Wazoo_St_312_interior.o
make Streets/Wazoo_St_412_front.o
make Streets/Wazoo_St_412_interior.o
make Streets/Wazoo_St_512_front.o
make Streets/Wazoo_St_512_interior.o
make Streets/Wazoo_St_612_front.o
make Streets/Wazoo_St_612_interior.o
make Streets/Wazoo_St_712_front.o
make Streets/Wazoo_St_712_interior.o
make Streets/Wazoo_St_812_front.o
make Streets/Wazoo_St_812_interior.o
make Streets/Wazoo_St_912_front.o
make Streets/Wazoo_St_912_interior.o
make Streets/Wazoo_St_cross.o
make Streets/Wazoo_St_e_end.o
make Streets/Wazoo_St_w_end.o
make Text/text-portdir.o
make Woods/Woods_1284.o
make Woods/Woods_5x.o
make Woods/Woods_5y.o
make new_Downtown/Downtown_3b.o
make new_Downtown/Downtown_5h.o
make new_Downtown/Downtown_6j.o
make new_Downtown/Downtown_7j.o
make new_Downtown/Downtown_9135.o
make new_Downtown/Downtown_9149.o
make teleports
