/* jshint esversion: 8 */
'use strict'

// GENERATED by lib/tools/parse_mud.js from the canonical C64 client
// muddle file (~/habitat-orig/habitat/Beta/Bak/beta.mud) — do not
// hand-edit; re-run the generator instead.
//
// Action slot semantics: 0-7 are the user verbs (DO, reverseDO, GO,
// STOP, GET, PUT, TALK, DESTROY — ACTION_* in lib/constants.js);
// slots 8+ are host-message handlers (avatar/region: slot number ==
// host message number) or class-internal chain targets. Entries are
// behavior names resolved against lib/behaviors at dispatch time so
// unported behaviors fail loudly rather than break the table load.
// Sound slots are carried as names only, for a future renderer.

const classes = {
  0: {
    name: 'class_region',
    typeName: 'Region',
    actions: [
      'illegal', // 0: do
      'illegal', // 1: reversed do
      'GoToNewRegion', // 2: go
      'generic_cease', // 3: stop
      'illegal', // 4: get
      'illegal', // 5: put
      'generic_broadcast', // 6: talk
      'illegal', // 7: destroy
      'transit_region', // 8: 8
      'toggle_ghost_mode', // 9: 9
      'boing', // 10: 10
      'boing', // 11: 11
      'boing', // 12: 12
      'change_player_color', // 13: 13
      'change_player_color', // 14: 14
      'ask_for_help', // 15: 15
      'ask_for_help', // 16: 16
      'boing', // 17: 17
      'do_a_gesture', // 18: 18
    ],
    sounds: ['error_beep', 'region_boing', 'footsteps', 'teleport_region_change_0', 'teleport_region_change_0_pw', 'teleport_region_change_1', 'teleport_region_change_1_pw', 'teleport_region_change_2', 'teleport_arrival', 'teleport_arrival_pw', 'region_change_music_v0', 'region_change_music_v1', 'region_change_music_v2'],
  },
  1: {
    name: 'class_avatar',
    typeName: 'Avatar',
    actions: [
      'avatar_do', // 0: do
      'noEffect', // 1: reversed do
      'avatar_go', // 2: go
      'generic_cease', // 3: stop
      'avatar_get', // 4: get
      'avatar_put', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'avatar_WALK', // 8: 8 -- WALK*
      'avatar_ATTACK', // 9: 9 -- ATTACK*
      'avatar_BASH', // 10: 10 -- BASH*
      'avatar_DIE', // 11: 11 -- DIE*
      'avatar_CLOSE', // 12: 12 -- CLOSE*
      'avatar_CLOSECONTAINER', // 13: 13 -- CLOSECONTAINER*
      'generic_SPEAK', // 14: 14 -- SPEAK*
      'avatar_GETM', // 15: 15 -- GET*
      'avatar_SITORGETUP', // 16: 16 -- SITORGETUP*
      'avatar_GRABFROM', // 17: 17 -- GRABFROM*
      'avatar_OPEN', // 18: 18 -- OPEN*
      'avatar_OPENCONTAINER', // 19: 19 -- OPENCONTAINER*
      'avatar_POSTURE', // 20: 20 -- POSTURE*
      'noEffect', // 21
      'avatar_PUTM', // 22: 22 -- PUT*
      'avatar_REINCARNATE', // 23: 23 -- REINCARNATE*
      'avatar_THROW', // 24: 24 -- THROW*
      'noEffect', // 25
      'noEffect', // 26
      'noEffect', // 27
      'avatar_WEAR', // 28: 28 -- WEAR*
      'avatar_REMOVE', // 29: 29 -- REMOVE*
      'avatar_PAID', // 30: 30 -- PAID*
    ],
    sounds: ['avatar_injured', 'avatar_injured_pw', 'avatar_killed', 'avatar_killed_pw', 'avatar_into_stone', 'avatar_out_of_stone', 'message_sent', 'message_sent', 'message_received', 'message_sent', 'clothes_donned', 'clothes_doffed'],
  },
  127: {
    name: 'class_head',
    typeName: 'Head',
    actions: [
      'head_do', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'head_get', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'generic_goToAndDropAt', // 8: 8 -- internal
    ],
    sounds: [],
  },
  3: {
    name: 'class_ghost',
    typeName: 'Ghost',
    actions: [
      'noEffect', // 0: do
      'illegal', // 1: reversed do
      'noEffect', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'illegal', // 8: 8
      'illegal', // 9: 9
      'illegal', // 10: 10
      'illegal', // 11: 11
      'illegal', // 12: 12
      'illegal', // 13: 13
      'generic_SPEAK', // 14: 14
    ],
    sounds: [],
  },
  2: {
    name: 'class_amulet',
    typeName: 'Amulet',
    actions: [
      'generic_doMagic', // 0: do
      'generic_rdoMagic', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['magic', 'magic_pw'],
  },
  129: {
    name: 'class_aquarium',
    typeName: 'Aquarium',
    actions: [
      'generic_depends', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'generic_CHANGESTATE', // 8: 8 -- CHANGESTATE*
    ],
    sounds: [],
  },
  4: {
    name: 'class_atm',
    typeName: 'Atm',
    actions: [
      'atm_do', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'atm_get', // 4: get
      'atm_put', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['money_into_atm', 'money_into_atm_pw', 'money_out_of_atm', 'money_out_of_atm_pw', 'atm_thinking'],
  },
  6: {
    name: 'class_bag',
    typeName: 'Bag',
    actions: [
      'generic_adjacentOpenCloseContainer', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndPickFromOrGet', // 4: get
      'generic_goToAndDropIntoIfOpen', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['bag_opening', 'bag_closing'],
  },
  7: {
    name: 'class_ball',
    typeName: 'Ball',
    actions: [
      'generic_depends', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  130: {
    name: 'class_bed',
    typeName: 'Bed',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goToFurniture', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndPickFrom', // 4: get
      'generic_goToAndDropInto', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  10: {
    name: 'class_book',
    typeName: 'Book',
    actions: [
      'book_do', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  11: {
    name: 'class_boomerang',
    typeName: 'Boomerang',
    actions: [
      'generic_depends', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  12: {
    name: 'class_bottle',
    typeName: 'Bottle',
    actions: [
      'generic_depends', // 0: do
      'bottle_rdo', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'bottle_FILL', // 8: 8
      'bottle_POUR', // 9: 9
    ],
    sounds: [],
  },
  13: {
    name: 'class_box',
    typeName: 'Box',
    actions: [
      'generic_adjacentOpenCloseContainer', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndPickFromOrGet', // 4: get
      'generic_goToAndDropIntoIfOpen', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['box_opening', 'box_closing'],
  },
  131: {
    name: 'class_bridge',
    typeName: 'Bridge',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goToCursor', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  132: {
    name: 'class_building',
    typeName: 'Building',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'sky_go', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  133: {
    name: 'class_bush',
    typeName: 'Bush',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  134: {
    name: 'class_chair',
    typeName: 'Chair',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goToFurniture', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndPickFrom', // 4: get
      'generic_goToAndDropInto', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  84: {
    name: 'class_changomatic',
    typeName: 'Changomatic',
    actions: [
      'generic_depends', // 0: do
      'changomatic_rdo', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'changomatic_CHANGE', // 8: 8 -- CHANGE*
    ],
    sounds: ['changomatic'],
  },
  135: {
    name: 'class_chest',
    typeName: 'Chest',
    actions: [
      'generic_adjacentOpenCloseContainer', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndPickFromIfOpen', // 4: get
      'generic_goToAndDropIntoIfOpen', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['chest_of_drawers_opening', 'chest_of_drawers_closing'],
  },
  16: {
    name: 'class_club',
    typeName: 'Club',
    actions: [
      'generic_depends', // 0: do
      'generic_strike', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  136: {
    name: 'class_coke_machine',
    typeName: 'Coke_machine',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'coke_machine_put', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'generic_PAY', // 8: 8 -- PAY*
      'generic_coinOp', // 9: 9 -- internal COKE_COINOP
    ],
    sounds: ['coin_accepted_by_coinop', 'coin_accepted_by_coinop_pw', 'coin_deposited_in_coinop', 'coin_deposited_in_coinop_pw', 'coin_rejected_by_coinop', 'coin_rejected_by_coinop_pw', 'stingy_coke_machine', 'stingy_coke_machine_pw'],
  },
  17: {
    name: 'class_compass',
    typeName: 'Compass',
    actions: [
      'generic_read', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  137: {
    name: 'class_couch',
    typeName: 'Couch',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goToFurniture', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndPickFrom', // 4: get
      'generic_goToAndDropInto', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  18: {
    name: 'class_countertop',
    typeName: 'Countertop',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndPickFrom', // 4: get
      'generic_goToAndDropInto', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  20: {
    name: 'class_crystal_ball',
    typeName: 'Crystal_ball',
    actions: [
      'generic_depends', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_askOracle', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['crystal_ball', 'crystal_ball_pw'],
  },
  21: {
    name: 'class_die',
    typeName: 'Die',
    actions: [
      'die_do', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'generic_CHANGESTATE', // 8: 8 -- ROLL*
    ],
    sounds: [],
  },
  22: {
    name: 'class_display_case',
    typeName: 'Display_case',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndPickFrom', // 4: get
      'generic_goToAndDropInto', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  23: {
    name: 'class_door',
    typeName: 'Door',
    actions: [
      'generic_adjacentOpenClose', // 0: do
      'illegal', // 1: reversed do
      'generic_goToOrPassThrough', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['door_opening', 'door_closing'],
  },
  24: {
    name: 'class_dropbox',
    typeName: 'Dropbox',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  25: {
    name: 'class_drugs',
    typeName: 'Drugs',
    actions: [
      'drugs_do', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'drugs_TAKE', // 8: 8
    ],
    sounds: [],
  },
  28: {
    name: 'class_elevator',
    typeName: 'Elevator',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'elevator_talk', // 6: talk
      'generic_destroy', // 7: destroy
      'illegal', // 8: 8 -- not used
      'elevator_ZAPIN', // 9: 9 -- ZAPIN*
      'elevator_ZAPTO', // 10: 10 -- ZAPTO*
    ],
    sounds: ['teleport_conf_wait', 'teleport_conf_wait_pw', 'teleport_departure', 'teleport_departure_pw', 'teleport_arrival', 'teleport_arrival_pw'],
  },
  26: {
    name: 'class_escape_device',
    typeName: 'Escape_device',
    actions: [
      'escape_device_do', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'escape_device_BUGOUT', // 8: 8
    ],
    sounds: ['escape_device_activates', 'escape_device_used_up'],
  },
  27: {
    name: 'class_fake_gun',
    typeName: 'Fake_gun',
    actions: [
      'fake_gun_do', // 0: do
      'fake_gun_rdo', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'fake_gun_FAKESHOOT', // 8: 8 -- FAKESHOOT*
      'fake_gun_RESET', // 9: 9 -- RESET*
    ],
    sounds: ['gun_safety_on', 'gun_safety_off', 'joke_gunshot', 'joke_gunshot_pw'],
  },
  138: {
    name: 'class_fence',
    typeName: 'Fence',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  29: {
    name: 'class_flag',
    typeName: 'Flag',
    actions: [
      'generic_depends', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_getMass', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'generic_CHANGESTATE', // 8: 8 -- CHANGESTATE+
    ],
    sounds: [],
  },
  30: {
    name: 'class_flashlight',
    typeName: 'Flashlight',
    actions: [
      'flashlight_do', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'generic_OFFLIGHT', // 8: 8 -- OFFLIGHT*
      'generic_ONLIGHT', // 9: 9 -- ONLIGHT*
    ],
    sounds: ['switch_click'],
  },
  139: {
    name: 'class_floor_lamp',
    typeName: 'Floor_lamp',
    actions: [
      'floor_lamp_do', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'generic_OFFLIGHT', // 8: 8 -- OFFLIGHT*
      'generic_ONLIGHT', // 9: 9 -- ONLIGHT*
    ],
    sounds: ['switch_click'],
  },
  140: {
    name: 'class_fortune_machine',
    typeName: 'Fortune_machine',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'fortune_machine_put', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'illegal', // 8
      'generic_coinOp', // 9: 9 -- internal COINOP
      'generic_PAY', // 10: 10
    ],
    sounds: ['coin_accepted_by_coinop', 'coin_accepted_by_coinop_pw', 'coin_deposited_in_coinop', 'coin_deposited_in_coinop_pw', 'coin_rejected_by_coinop', 'coin_rejected_by_coinop_pw', 'fortune_dispensed', 'fortune_dispensed_pw', 'parking_meter_crank', 'parking_meter_crank_pw'],
  },
  141: {
    name: 'class_fountain',
    typeName: 'Fountain',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndFill', // 4: get
      'noEffect', // 5: put
      'generic_askOracle', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  158: {
    name: 'class_bureaucrat',
    typeName: 'Bureaucrat',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_askOracle', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  31: {
    name: 'class_frisbee',
    typeName: 'Frisbee',
    actions: [
      'generic_depends', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  5: {
    name: 'class_game_piece',
    typeName: 'Game_piece',
    actions: [
      'generic_chgState', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'telekenesis_get', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'generic_CHANGESTATE', // 8: 8 -- CHANGESTATE*
    ],
    sounds: ['magic_2', 'magic_2_pw'],
  },
  32: {
    name: 'class_garbage_can',
    typeName: 'Garbage_can',
    actions: [
      'garbage_can_do', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndPickFrom', // 4: get
      'generic_goToAndDropInto', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'garbage_can_FLUSH', // 8: 8 -- FLUSH*
    ],
    sounds: ['garbage_can_flushing'],
  },
  33: {
    name: 'class_gemstone',
    typeName: 'Gemstone',
    actions: [
      'generic_doMagicIfMagic', // 0: do
      'generic_rdoMagicIfMagic', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['magic_2', 'magic_2_pw'],
  },
  35: {
    name: 'class_grenade',
    typeName: 'Grenade',
    actions: [
      'grenade_do', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'grenade_EXPLODE', // 8: 8 -- EXPLODE+
    ],
    sounds: ['big_explosion', 'big_explosion_pw'],
  },
  36: {
    name: 'class_ground',
    typeName: 'Ground',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goToCursor', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'generic_goToAndDropAt', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  37: {
    name: 'class_gun',
    typeName: 'Gun',
    actions: [
      'gun_do', // 0: do
      'generic_shoot', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['gun_safety_on', 'gun_safety_off', 'gunshot'],
  },
  38: {
    name: 'class_hand_of_god',
    typeName: 'Hand_of_god',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'illegal', // 2: go
      'illegal', // 3: stop
      'illegal', // 4: get
      'illegal', // 5: put
      'illegal', // 6: talk
      'generic_destroy', // 7: destroy
      'hand_of_god_BLAST', // 8: 8 -- BLAST*
    ],
    sounds: ['hand_o_god_flame', 'hand_o_god_lightning', 'hand_o_god_lightning_pw'],
  },
  39: {
    name: 'class_hat',
    typeName: 'Hat',
    actions: [
      'generic_depends', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  88: {
    name: 'class_hole',
    typeName: 'Hole',
    actions: [
      'hole_do', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndPickFromIfOpen', // 4: get
      'generic_goToAndDropIntoIfOpen', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'generic_adjacentOpenCloseContainer', // 8: 8 -- internal
    ],
    sounds: ['box_opening', 'box_closing'],
  },
  143: {
    name: 'class_house_cat',
    typeName: 'House_cat',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  144: {
    name: 'class_hot_tub',
    typeName: 'Hot_tub',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goToCursor', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndFill', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  93: {
    name: 'class_flat',
    typeName: 'Flat',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'trap_go', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'trap_put', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'sky_go', // 8: 8 - internal
      'wall_go', // 9: 9 - internal
      'generic_goToCursor', // 10: 10 - internal
      'noEffect', // 11: 11 - internal
    ],
    sounds: [],
  },
  40: {
    name: 'class_instant_object_pill',
    typeName: 'Instant_object_pill',
    actions: [
      'generic_depends', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'instant_object_TRANSFORM', // 8: 8 -- TRANSFORM*
    ],
    sounds: ['instant_object_pill'],
  },
  145: {
    name: 'class_jukebox',
    typeName: 'Jukebox',
    actions: [
      'jukebox_do', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'jukebox_put', // 5: put
      'jukebox_talk', // 6: talk
      'generic_destroy', // 7: destroy
      'generic_PAY', // 8: 8
      'jukebox_PLAY', // 9: 9 -- PLAY+
      'generic_coinOp', // 10: 10 -- internal JUKEBOX_COINOP
    ],
    sounds: [],
  },
  42: {
    name: 'class_key',
    typeName: 'Key',
    actions: [
      'key_do', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  43: {
    name: 'class_knick_knack',
    typeName: 'Knick_knack',
    actions: [
      'generic_doMagicIfMagic', // 0: do
      'generic_rdoMagicIfMagic', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['magic_3', 'magic_3_pw'],
  },
  44: {
    name: 'class_knife',
    typeName: 'Knife',
    actions: [
      'generic_depends', // 0: do
      'generic_strike', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  45: {
    name: 'class_magic_lamp',
    typeName: 'Magic_lamp',
    actions: [
      'magic_lamp_do', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'magic_lamp_talk', // 6: talk
      'generic_destroy', // 7: destroy
      'magic_lamp_WISH', // 8: 8 -- WISH*
      'magic_lamp_RUB', // 9: 9 -- RUB*
    ],
    sounds: ['genie_appears', 'genie_out'],
  },
  46: {
    name: 'class_magic_staff',
    typeName: 'Magic_staff',
    actions: [
      'generic_doMagic', // 0: do
      'generic_rdoMagic', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['magic_4', 'magic_4_pw'],
  },
  97: {
    name: 'class_magic_immobile',
    typeName: 'Magic_immobile',
    actions: [
      'generic_adjacentDoMagic', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'button_CHANGESTATE', // 8: 8
    ],
    sounds: ['magic_4', 'magic_4_pw'],
  },
  98: {
    name: 'class_glue',
    typeName: 'Glue',
    actions: [
      'illegal', // 0: do
      'illegal', // 1: reversed do
      'illegal', // 2: go
      'illegal', // 3: stop
      'illegal', // 4: get
      'illegal', // 5: put
      'illegal', // 6: talk
      'illegal', // 7: destroy
    ],
    sounds: [],
  },
  47: {
    name: 'class_magic_wand',
    typeName: 'Magic_wand',
    actions: [
      'generic_doMagic', // 0: do
      'generic_rdoMagic', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['magic', 'magic_pw'],
  },
  48: {
    name: 'class_mailbox',
    typeName: 'Mailbox',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  49: {
    name: 'class_matchbook',
    typeName: 'Matchbook',
    actions: [
      'generic_read', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  52: {
    name: 'class_movie_camera',
    typeName: 'Movie_camera',
    actions: [
      'generic_switch', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'generic_OFF', // 8: 8 -- OFF*
      'generic_ON', // 9: 9 -- ON*
    ],
    sounds: ['switch_click', 'switch_click'],
  },
  54: {
    name: 'class_paper',
    typeName: 'Paper',
    actions: [
      'paper_do', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['successful_esp_activation'],
  },
  96: {
    name: 'class_pawn_machine',
    typeName: 'Pawn_machine',
    actions: [
      'pawn_machine_do', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndPickFrom', // 4: get
      'generic_goToAndDropInto', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'pawn_machine_MUNCH', // 8: 8 -- MUNCH
    ],
    sounds: ['pawn_machine_munching', 'pawn_machine_munching_pw'],
  },
  55: {
    name: 'class_plaque',
    typeName: 'Plaque',
    actions: [
      'plaque_do', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'illegal', // 4: get
      'illegal', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  56: {
    name: 'class_short_sign',
    typeName: 'Short_sign',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  57: {
    name: 'class_sign',
    typeName: 'Sign',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  58: {
    name: 'class_plant',
    typeName: 'Plant',
    actions: [
      'generic_depends', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_getMass', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  147: {
    name: 'class_pond',
    typeName: 'Pond',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndFill', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  60: {
    name: 'class_ring',
    typeName: 'Ring',
    actions: [
      'generic_doMagic', // 0: do
      'generic_rdoMagic', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['magic_2', 'magic_2_pw'],
  },
  148: {
    name: 'class_river',
    typeName: 'River',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndFill', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  61: {
    name: 'class_rock',
    typeName: 'Rock',
    actions: [
      'generic_depends', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_getMass', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  149: {
    name: 'class_roof',
    typeName: 'Roof',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'noEffect', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  150: {
    name: 'class_safe',
    typeName: 'Safe',
    actions: [
      'generic_adjacentOpenCloseContainer', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndPickFromIfOpen', // 4: get
      'generic_goToAndDropIntoIfOpen', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['box_opening', 'box_closing'],
  },
  63: {
    name: 'class_security_device',
    typeName: 'Security_device',
    actions: [
      'generic_switch', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'generic_OFF', // 8: 8 -- OFF*
      'generic_ON', // 9: 9 -- ON*
    ],
    sounds: ['security_device_on', 'security_device_off'],
  },
  64: {
    name: 'class_sensor',
    typeName: 'Sensor',
    actions: [
      'sensor_do', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'sensor_SCAN', // 8: 8 -- SCAN*
    ],
    sounds: ['sensor_scanning', 'sensor_didnt_find_it', 'sensor_found_it'],
  },
  90: {
    name: 'class_sex_changer',
    typeName: 'Sex_changer',
    actions: [
      'sex_changer_do', // 0: do
      'illegal', // 1: reversed do
      'sex_changer_go', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'sex_changer_SEXCHANGE', // 8: 8 -- SEXCHANGE*
    ],
    sounds: ['sex_changer', 'sex_changer_pw'],
  },
  89: {
    name: 'class_shovel',
    typeName: 'Shovel',
    actions: [
      'generic_depends', // 0: do
      'shovel_rdo', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'shovel_DIG', // 8: 8 -- DIG*
    ],
    sounds: ['digging'],
  },
  95: {
    name: 'class_spray_can',
    typeName: 'Spray_can',
    actions: [
      'spray_can_do', // 0: do
      'noEffect', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'spray_can_SPRAY', // 8: 8 -- SPRAY*
    ],
    sounds: ['spray_can_hiss'],
  },
  152: {
    name: 'class_picture',
    typeName: 'Picture',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  69: {
    name: 'class_sky',
    typeName: 'Sky',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'sky_go', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  70: {
    name: 'class_stereo',
    typeName: 'Stereo',
    actions: [
      'generic_switch', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'stereo_get', // 4: get
      'stereo_put', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'stereo_UNLOAD', // 8: 8
      'stereo_PLAY', // 9: 9 -- PLAY+
    ],
    sounds: ['switch_click', 'switch_click'],
  },
  153: {
    name: 'class_street',
    typeName: 'Street',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goToCursor', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'generic_goToAndDropAt', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  154: {
    name: 'class_streetlamp',
    typeName: 'Streetlamp',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  91: {
    name: 'class_stun_gun',
    typeName: 'Stun_gun',
    actions: [
      'gun_do', // 0: do
      'stun_gun_rdo', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: ['gun_safety_on', 'gun_safety_off', 'stun_gun_fire', 'stun_gun_fire_pw', 'stun_gun_hit', 'stun_gun_hit_pw', 'stun_gun_miss'],
  },
  155: {
    name: 'class_table',
    typeName: 'Table',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndPickFrom', // 4: get
      'generic_goToAndDropInto', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  71: {
    name: 'class_tape',
    typeName: 'Tape',
    actions: [
      'generic_read', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'tape_LOAD', // 8: 8
    ],
    sounds: [],
  },
  74: {
    name: 'class_teleport_booth',
    typeName: 'Teleport',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'teleport_put', // 5: put
      'teleport_talk', // 6: talk
      'generic_destroy', // 7: destroy
      'teleport_PAY', // 8: 8 -- PAY*
      'teleport_ZAPIN', // 9: 9 -- ZAPIN*
      'teleport_ZAPTO', // 10: 10 -- ZAPTO*
      'generic_coinOp', // 11: 11 -- internal TELEPORT_COINOP
    ],
    sounds: ['coin_accepted_by_coinop', 'coin_accepted_by_coinop_pw', 'coin_deposited_in_coinop', 'coin_deposited_in_coinop_pw', 'coin_rejected_by_coinop', 'coin_rejected_by_coinop_pw', 'teleport_activates', 'teleport_activates_pw', 'teleport_conf_wait', 'teleport_conf_wait_pw', 'teleport_departure', 'teleport_departure_pw', 'teleport_arrival', 'teleport_arrival_pw'],
  },
  94: {
    name: 'class_test',
    typeName: 'Test',
    actions: [
      'generic_test', // 0: do
      'generic_test', // 1: reversed do
      'generic_test', // 2: go
      'generic_cease', // 3: stop
      'generic_test', // 4: get
      'generic_test', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  75: {
    name: 'class_ticket',
    typeName: 'Ticket',
    actions: [
      'generic_read', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  76: {
    name: 'class_tokens',
    typeName: 'Tokens',
    actions: [
      'tokens_do', // 0: do
      'tokens_rdo', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  87: {
    name: 'class_trapezoid',
    typeName: 'Trapezoid',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'trap_go', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'trap_put', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'sky_go', // 8: 8 - internal
      'wall_go', // 9: 9 - internal
      'generic_goToCursor', // 10: 10 - internal
      'noEffect', // 11: 11 - internal
    ],
    sounds: [],
  },
  92: {
    name: 'class_super_trapezoid',
    typeName: 'Super_trapezoid',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'trap_go', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'trap_put', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'sky_go', // 8: 8 - internal
      'wall_go', // 9: 9 - internal
      'generic_goToCursor', // 10: 10 - internal
      'noEffect', // 11: 11 - internal
    ],
    sounds: [],
  },
  156: {
    name: 'class_tree',
    typeName: 'Tree',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  85: {
    name: 'class_vendo_front',
    typeName: 'Vendo_front',
    actions: [
      'vendo_do', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'vendo_put', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'vendo_SELECT', // 8: 8 -- SELECT*
      'vendo_SELL', // 9: 9 -- SELL*
      'generic_coinOp', // 10: 10 -- internal
    ],
    sounds: ['coin_accepted_by_coinop', 'coin_accepted_by_coinop_pw', 'coin_deposited_in_coinop', 'coin_deposited_in_coinop_pw', 'coin_rejected_by_coinop', 'coin_rejected_by_coinop_pw', 'vendo_changing', 'vendo_dispensing', 'vendo_dispensing_pw'],
  },
  86: {
    name: 'class_vendo_inside',
    typeName: 'Vendo_inside',
    actions: [
      'illegal', // 0: do
      'illegal', // 1: reversed do
      'illegal', // 2: go
      'illegal', // 3: stop
      'illegal', // 4: get
      'illegal', // 5: put
      'illegal', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  80: {
    name: 'class_wall',
    typeName: 'Wall',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'wall_go', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  157: {
    name: 'class_window',
    typeName: 'Window',
    actions: [
      'generic_depends', // 0: do
      'illegal', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'noEffect', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
    ],
    sounds: [],
  },
  82: {
    name: 'class_wind_up_toy',
    typeName: 'Windup_toy',
    actions: [
      'windup_toy_do', // 0: do
      'generic_throw', // 1: reversed do
      'generic_goTo', // 2: go
      'generic_cease', // 3: stop
      'generic_goToAndGet', // 4: get
      'noEffect', // 5: put
      'generic_broadcast', // 6: talk
      'generic_destroy', // 7: destroy
      'windup_toy_WIND', // 8: 8 -- WIND*
    ],
    sounds: ['winding_up_toy', 'winding_up_toy_pw'],
  },
  255: {
    name: 'class_zone',
    typeName: 'Zone',
    actions: [
    ],
    sounds: [],
  },
}

const byTypeName = {}
for (const [num, entry] of Object.entries(classes)) {
  byTypeName[entry.typeName] = parseInt(num, 10)
}

module.exports = { classes, byTypeName }
